package view;

public enum Const_Size {

	CREATE_UNIT_FRAME_SIZE(144),
	CREATE_UNIT_FRAME_POS(12),

	CREATE_UNIT_IMAGE_POS(24),

	CREATE_BUTTON_WIDTH(144),
	CREATE_BUTTON_HEIGHT(72),

	CREATE_BUTTON_POS_X(516),
	CREATE_BUTTON_POS_Y(180),
	CREATE_BUTTON_SPACE(12),

	CREATE_TOOLBAR_SIZE(168),
	CREATE_TOOLBAR_STROKE(6),
	CREATE_TOOLBAR_STROKE_MINI(2),

	CREATE_FIELD_WIDTH(504),
	CREATE_FIELD_HEIGHT(504),


	TITLE_CREATE_POS_X(96),
	TITLE_CREATE_POS_Y(448),
	TITLE_CREATE_WIDTH(144),
	TITLE_CREATE_HEIGHT(72),

	TITLE_PLAY_POS_X(432),
	TITLE_PLAY_POS_Y(448),
	TITLE_PLAY_WIDTH(144),
	TITLE_PLAY_HEIGHT(72),

	TITLLE_CURSOR_WIDTH(32),
	TITLLE_CURSOR_HEIGHT(32),


	PLAYER_WIDTH(72),
	PLAYER_HEIGHT(54),
	PLAYER_BASESIZE(72),

	UNIT_BASESIZE(96),
	UNIT_SMALLSIZE(72),


	SCREEN_WIDTH(672),
	SCREEN_HEIGHT(672);


	private int cnt;
	private Const_Size(int cnt) {
		this.cnt = cnt;
	}

	public int getCnt() {
		return cnt;
	}
}
